 - name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Deploy Docker Container
    command: docker run -itd -p 8085:8081 jayant2327/application:latest
